trainer_name: CrowdES_trainer
crowd_emitter:
  emitter_pre:
    augmentation: ["hflip", "vflip", "tp", "rev"]
    cache_dir: "./cache/"
    checkpoint_dir: "./checkpoints/{}/emitter_pre/"
    model_pretrained: "./checkpoints/pretrained/segformer-b0-finetuned-cityscapes-1024-1024/"
    blur_sigma: 15
    train_batch_size: 8
    eval_batch_size: 8
    gradient_accumulation_steps: 1
    num_train_epochs: 128
    lr_scheduler_type: "polynomial"
    learning_rate: 0.0001
    num_warmup_steps: 0
    seed: 0
    use_logger: false
    logger_type: "wandb"

  emitter:
    checkpoint_dir: "./checkpoints/{}/emitter/"
    train_batch_size: 512
    eval_batch_size: 10
    gradient_accumulation_steps: 1
    num_train_epochs: 256
    lr_scheduler_type: "polynomial"
    learning_rate: 0.0001
    num_warmup_steps: 0
    seed: 0
    use_logger: false
    logger_type: "wandb"

crowd_simulator:
  simulator:
    checkpoint_dir: "./checkpoints/{}/dynamics/"
    train_batch_size: 2048
    eval_batch_size: 2048
    gradient_accumulation_steps: 1
    num_train_epochs: 64
    lr_scheduler_type: "polynomial"
    learning_rate: 0.0001
    num_warmup_steps: 0
    seed: 0
    use_logger: false
    logger_type: "wandb"
