dataset_name: edin
dataset_family: edinburgh
dataset_path: ./datasets/EDIN/
dataset_preprocessor: EDINPreprocessor
dataset_preprocessed_path: /data/Crowd_Generation/datasets/preprocessed/edin/
dataset_augmentation: ["rev"]
dataset_fps: 10
dataset_test:
  - tracks.06Dec
  - tracks.11Dec
  - tracks.14Dec
  - tracks.15Dec
  - tracks.16Dec
  - tracks.18Dec
  - tracks.19Dec
  - tracks.20Dec
  - tracks.21Dec
  - tracks.22Dec
  - tracks.23Dec
  - tracks.24Dec
  - tracks.29Dec
  - tracks.30Dec
  - tracks.31Dec
dataset_train:
  - tracks.24Aug
  - tracks.25Aug
  - tracks.26Aug
  - tracks.27Aug
  - tracks.28Aug
  - tracks.29Aug
  - tracks.01Sep
  - tracks.02Sep
  - tracks.04Sep
  - tracks.05Sep
  - tracks.06Sep
  - tracks.10Sep
  - tracks.11Sep
  - tracks.12Sep
  - tracks.13Sep
  - tracks.14Sep
  - tracks.16Sep
  - tracks.18Sep
  - tracks.19Sep
  - tracks.20Sep
  - tracks.21Sep
  - tracks.22Sep
  - tracks.23Sep
  - tracks.24Sep
  - tracks.25Sep
  - tracks.27Sep
  - tracks.28Sep
  - tracks.29Sep
  - tracks.30Sep
  - tracks.02Oct
  - tracks.03Oct
  - tracks.04Oct
  - tracks.05Oct
  - tracks.06Oct
  - tracks.07Oct
  - tracks.08Oct
  - tracks.09Oct
  - tracks.10Oct
  - tracks.11Oct
  - tracks.12Oct
  - tracks.13Oct
  - tracks.14Oct
  - tracks.15Oct
  - tracks.01Jan
  - tracks.02Jan
  - tracks.04Jan
  - tracks.06Jan
  - tracks.07Jan
  - tracks.08Jan
  - tracks.10Jan
  - tracks.11Jan
  - tracks.12Jan
  - tracks.13Jan
  - tracks.14Jan
  - tracks.15Jan
  - tracks.16Jan
  - tracks.17Jan
  - tracks.18Jan
  - tracks.19Jan
  - tracks.29May
  - tracks.30May
  - tracks.31May
  - tracks.02Jun
  - tracks.03Jun
  - tracks.04Jun
  - tracks.05Jun
  - tracks.06Jun
  - tracks.08Jun
  - tracks.09Jun
  - tracks.11Jun
  - tracks.12Jun
  - tracks.14Jun
  - tracks.16Jun
  - tracks.17Jun
  - tracks.18Jun
  - tracks.20Jun
  - tracks.22Jun
  - tracks.24Jun
  - tracks.25Jun
  - tracks.26Jun
  - tracks.29Jun
  - tracks.30Jun
  - tracks.01Jul
  - tracks.02Jul
  - tracks.04Jul
  - tracks.11Jul
  - tracks.12Jul
  - tracks.13Jul
  - tracks.14Jul
  - tracks.17Jul
  - tracks.18Jul
  - tracks.19Jul
  - tracks.20Jul
  - tracks.21Jul
  - tracks.22Jul
  - tracks.23Jul
  - tracks.25Jul
  - tracks.26Jul
  - tracks.27Jul
  - tracks.28Jul
  - tracks.29Jul
  - tracks.30Jul
  - tracks.01Aug