dataset_name: zara2
dataset_family: ethucy
dataset_path: ./datasets/ETH-UCY/
dataset_preprocessor: ETHUCYPreprocessor
dataset_preprocessed_path: /data/Crowd_Generation/datasets/preprocessed/zara2/
dataset_augmentation: ['hflip', 'vflip', 'tp', 'rev']
dataset_fps: 25
dataset_test:
  - crowds_zara02
dataset_train:
  - seq_eth
  - seq_hotel
  - students001
  - students003
  - crowds_zara01
  - crowds_zara03